### ISSUE TITLE
Build error on Arch linux

### ISSUE THREAD

**Issue by petrkr** [labapart/gattlib#171]
git clone `https://github.com/labapart/gattlib/`

```
[petrkr@pkdell build (master=)]$ cat /tmp/sphinx-err-l640ecfs.log
# Sphinx version: 2.4.4
# Python version: 3.8.2 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.11.1
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 245, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 397, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 465, in load_extension
    metadata = setup(app)
  File "/usr/lib/python3.8/site-packages/breathe/__init__.py", line 13, in setup
    from . import directives
  File "/usr/lib/python3.8/site-packages/breathe/directives.py", line 4, in <module>
    from .renderer import DoxygenToRstRendererFactory
  File "/usr/lib/python3.8/site-packages/breathe/renderer/__init__.py", line 5, in <module>
    from . import sphinxrenderer
  File "/usr/lib/python3.8/site-packages/breathe/renderer/sphinxrenderer.py", line 74, in <module>
    class DomainDirectiveFactory(object):
  File "/usr/lib/python3.8/site-packages/breathe/renderer/sphinxrenderer.py", line 90, in DomainDirectiveFactory
    'define': (c.CMacroObject, 'macro'),
AttributeError: module 'sphinx.domains.c' has no attribute 'CMacroObject'
```

**Comment by petrkr** [comment]
Workaround for now is build it without documentation `cmake -DGATTLIB_BUILD_DOCS=OFF ../`

**Comment by petrkr** [comment]
closing with workaround, not relevant anymore
